/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/splas/tinyEtherDeveloper/FPGA_project/L2Switch/al_ip/CTRL_FRAME_FIFO.v
 ** Date	:	2022 08 11
 ** TD version	:	4.4.433
\************************************************************/

`timescale 1ns / 1ps

module CTRL_FRAME_RAM ( 
	doa, dia, addra, clka, wea, rsta, 
	dob, dib, addrb, clkb, web, rstb
);

	output [31:0] doa;
	output [31:0] dob;


	input  [31:0] dia;
	input  [31:0] dib;
	input  [9:0] addra;
	input  [9:0] addrb;
	input  [3:0] wea;
	input  [3:0] web;
	input  clka;
	input  clkb;
	input  rsta;
	input  rstb;




	EG_LOGIC_BRAM #( .DATA_WIDTH_A(32),
				.DATA_WIDTH_B(32),
				.ADDR_WIDTH_A(10),
				.ADDR_WIDTH_B(10),
				.DATA_DEPTH_A(1024),
				.DATA_DEPTH_B(1024),
				.BYTE_ENABLE(8),
				.BYTE_A(4),
				.BYTE_B(4),
				.MODE("DP"),
				.REGMODE_A("NOREG"),
				.REGMODE_B("NOREG"),
				.WRITEMODE_A("NORMAL"),
				.WRITEMODE_B("NORMAL"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K"),
				.INIT_FILE("NONE"),
				.FILL_ALL("00000000000000000000000000000000"))
			inst(
				.dia(dia),
				.dib(dib),
				.addra(addra),
				.addrb(addrb),
				.cea(1'b1),
				.ceb(1'b1),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(clkb),
				.wea(1'b0),
				.bea(wea),
				.web(1'b0),
				.beb(web),
				.rsta(rsta),
				.rstb(rstb),
				.doa(doa),
				.dob(dob));


endmodule