/* used in Header_FIFO implementation. */

/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/splas/tinyEtherDeveloper/FPGA_project/L2Switch/al_ip/HEADER_FIFO.v
 ** Date	:	2022 07 25
 ** TD version	:	4.4.433
\************************************************************/

`timescale 1ns / 1ps

module HEADER_FIFO #(
	parameter WIDTH = 128
)(
	rst,
	di, clk, we,
	do, re,
	empty_flag,
	full_flag
);

	input rst;
	input [WIDTH-1:0] di;
	input clk, we;
	input re;

	output wire [WIDTH-1:0] do;
	output wire empty_flag;
	output wire full_flag;

	RTL_SYNC_FIFO #(
		.DATA_WIDTH(128),
		.FIFO_DEPTH_POWER(8), // 14:16384, 15:32768, 16:65536
		.AFULL_CNT(200),
		.AEMPTY_CNT(10)  
	) raw_header_rtl_fifo (
		.full_flag(full_flag),       // buffer write ready
		.empty_flag(empty_flag),       // buffer read ready
		.afull_flag(),
		.aempty_flag(),
		.din(di),       // read data out

		.dout(do),       // write data in
		.wen(we),       // write enable
		.ren(re),       // read enable
		.clk(clk),       // clock
		.rst(rst)); 

endmodule
