/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/splas/tinyEtherDeveloper/FPGA_project/L2Switch/al_ip/ram_dp_ip.v
 ** Date	:	2022 07 23
 ** TD version	:	4.4.433
\************************************************************/

// `timescale 1ns / 1ps

module ram_dp_ip # (
	parameter DATA_WIDTH = 32,
	parameter ADDR_WIDTH = 10
)( 
	a_dout, a_din, a_addr, a_clk, a_we, a_rst, 
	b_dout, b_din, b_addr, b_clk, b_we, b_rst
);

	output [31:0] a_dout;
	output [31:0] b_dout;


	input  [31:0] a_din;
	input  [31:0] b_din;
	input  [9:0] a_addr;
	input  [9:0] b_addr;
	input  a_we;
	input  b_we;
	input  a_clk;
	input  b_clk;
	input  a_rst;
	input  b_rst;




	EG_LOGIC_BRAM #( .DATA_WIDTH_A(DATA_WIDTH),
				.DATA_WIDTH_B(DATA_WIDTH),
				.ADDR_WIDTH_A(ADDR_WIDTH),
				.ADDR_WIDTH_B(ADDR_WIDTH),
				.DATA_DEPTH_A(2**ADDR_WIDTH),
				.DATA_DEPTH_B(2**ADDR_WIDTH),
				.MODE("DP"),
				.REGMODE_A("NOREG"),
				.REGMODE_B("NOREG"),
				.WRITEMODE_A("WRITETHROUGH"),
				.WRITEMODE_B("WRITETHROUGH"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K(FAST)"),
				.INIT_FILE("NONE"),
				.FILL_ALL("00000000000000000000000000000000"))
			inst(
				.dia(a_din),
				.dib(b_din),
				.addra(a_addr),
				.addrb(b_addr),
				.cea(1'b1),
				.ceb(1'b1),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(a_clk),
				.clkb(b_clk),
				.wea(a_we),
				.web(b_we),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(a_rst),
				.rstb(b_rst),
				.doa(a_dout),
				.dob(b_dout));


endmodule