/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/osamu/Desktop/tinyEtherDeveloper/RTL_project/common/al_ip/raw_async_9b_fifo.v
 ** Date	:	2022 08 28
 ** TD version	:	4.6.14756
\************************************************************/

`timescale 1ns / 1ps

module raw_async_9b_fifo (
	rst,
	di, clkw, we,
	do, clkr, re,
	empty_flag, aempty_flag,
	full_flag, afull_flag 
);

	input rst;
	input [8:0] di;
	input clkw, we;
	input clkr,re;

	output [8:0] do;
	output empty_flag, aempty_flag;
	output full_flag, afull_flag;

EG_LOGIC_FIFO #(
 	.DATA_WIDTH_W(9),
	.DATA_WIDTH_R(9),
	.DATA_DEPTH_W(8192),
	.DATA_DEPTH_R(8192),
	.ENDIAN("BIG"),
	.RESETMODE("ASYNC"),
	.E(0),
	.F(8192),
	.ASYNC_RESET_RELEASE("ASYNC"),
	.AE(32),
	.AF(6600))
logic_fifo(
	.rst(rst),
	.di(di),
	.clkw(clkw),
	.we(we),
	.csw(3'b111),
	.do(do),
	.clkr(clkr),
	.re(re),
	.csr(3'b111),
	.ore(1'b0),
	.empty_flag(empty_flag),
	.aempty_flag(aempty_flag),
	.full_flag(full_flag),
	.afull_flag(afull_flag)

);

endmodule