--------------------------------------------------------------
 --  Copyright (c) 2011-2021 Anlogic, Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	C:/Users/osamu/Desktop/tinyEtherDeveloper/RTL_project/common/al_ip/raw_async_9b_fifo.vhd
 -- Date	:	2022 08 28
 -- TD version	:	4.6.14756
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY raw_async_9b_fifo IS
PORT (
	di	: IN STD_LOGIC_VECTOR(8 DOWNTO 0);

	rst	: IN STD_LOGIC;
	clkw	: IN STD_LOGIC;
	we	: IN STD_LOGIC;
	clkr	: IN STD_LOGIC;
	re	: IN STD_LOGIC;
	do	: OUT STD_LOGIC_VECTOR(8 DOWNTO 0);
	empty_flag		: OUT STD_LOGIC;
	aempty_flag		: OUT STD_LOGIC;
	full_flag		: OUT STD_LOGIC;
	afull_flag		: OUT STD_LOGIC
	);
END raw_async_9b_fifo;

ARCHITECTURE struct OF raw_async_9b_fifo IS

	BEGIN
	inst : EG_LOGIC_FIFO
		GENERIC MAP (
			DATA_WIDTH_W			=> 9,
			DATA_DEPTH_W			=> 8192,
			DATA_WIDTH_R			=> 9,
			DATA_DEPTH_R			=> 8192,
			ENDIAN				=> "BIG",
			RESETMODE			=> "ASYNC",
			REGMODE_R			=> "NOREG",
			E					=> 0,
			F					=> 8192,
			ASYNC_RESET_RELEASE	=> "ASYNC",
			AE					=> 32,
			AF					=> 6600
		)
		PORT MAP (
			rst	=> rst,
			di	=> di,
			clkw	=> clkw,
			we	=> we,
			csw	=> "111",
			clkr	=> clkr,
			ore	=> '0',
			re	=> re,
			csr	=> "111",
			do	=> do,
			empty_flag	=> empty_flag,
			aempty_flag	=> aempty_flag,
			full_flag	=> full_flag,
			afull_flag	=> afull_flag
		);

END struct;
